import { StyleSheet } from 'react-native';
import { BLUE, DEEP, GOLD, BG, DARK, GRAY, RED, GREEN } from './theme';

export const s = StyleSheet.create({
  container: { flex: 1, backgroundColor: BG },

  header: { paddingTop: 56, paddingBottom: 56, paddingHorizontal: 16, overflow: 'hidden' },
  subHeader: { paddingTop: 52, paddingBottom: 28, paddingHorizontal: 16, overflow: 'hidden' },
  subRow: { flexDirection: 'row-reverse', alignItems: 'center', gap: 12 },
  subTitle: { color: '#fff', fontSize: 20, fontWeight: '700' },
  deco1: { position: 'absolute', width: 200, height: 200, borderRadius: 100, backgroundColor: 'rgba(255,184,0,0.16)', top: -70, left: -60 },
  deco2: { position: 'absolute', width: 120, height: 120, borderRadius: 60, backgroundColor: 'rgba(255,255,255,0.07)', top: 50, left: 110 },
  deco3: { position: 'absolute', width: 90, height: 90, borderRadius: 45, backgroundColor: 'rgba(255,184,0,0.22)', bottom: -30, right: 40 },
  topBar: { flexDirection: 'row-reverse', justifyContent: 'space-between', marginBottom: 16 },
  iconRow: { flexDirection: 'row', gap: 8 },
  circle: { width: 40, height: 40, borderRadius: 20, backgroundColor: 'rgba(255,255,255,0.18)', borderWidth: 1, borderColor: 'rgba(255,184,0,0.5)', alignItems: 'center', justifyContent: 'center' },
  circleGold: { width: 40, height: 40, borderRadius: 20, backgroundColor: GOLD, alignItems: 'center', justifyContent: 'center', elevation: 4 },
  greeting: { color: '#fff', fontSize: 22, fontWeight: '700', textAlign: 'right' },
  sub: { color: '#FFE08A', fontSize: 14, textAlign: 'right', marginTop: 4 },

  card: { backgroundColor: '#fff', marginHorizontal: 16, marginTop: -32, borderRadius: 16, padding: 16, elevation: 5, shadowColor: '#000', shadowOpacity: 0.1, shadowRadius: 10, borderTopWidth: 3, borderTopColor: GOLD },
  label: { color: GRAY, fontSize: 14, textAlign: 'right', marginTop: 8 },
  accountRow: { flexDirection: 'row-reverse', justifyContent: 'space-between', alignItems: 'center', marginTop: 4 },
  account: { color: DARK, fontSize: 18, fontWeight: '600', textAlign: 'right' },
  copyBtn: { flexDirection: 'row', alignItems: 'center', gap: 4, paddingVertical: 4, paddingHorizontal: 8, borderRadius: 8, backgroundColor: '#E6EEFA' },
  copyText: { fontSize: 12, fontWeight: '600' },
  balanceBox: { marginTop: 8, borderRadius: 14, paddingVertical: 14, paddingHorizontal: 16, flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', borderWidth: 1, borderColor: 'rgba(255,184,0,0.65)' },
  balance: { color: '#fff', fontSize: 30, fontWeight: '800' },
  currency: { color: GOLD, fontSize: 18, fontWeight: '700' },

  actions: { flexDirection: 'row-reverse', justifyContent: 'space-around', marginTop: 24, paddingHorizontal: 8 },
  action: { alignItems: 'center', width: 76 },
  actionBox: { width: 60, height: 60, borderRadius: 18, alignItems: 'center', justifyContent: 'center', borderWidth: 1.5, borderColor: GOLD, elevation: 4, shadowColor: BLUE, shadowOpacity: 0.3, shadowRadius: 6 },
  actionLabel: { color: DARK, fontSize: 12, marginTop: 8, textAlign: 'center', fontWeight: '600' },

  sectionHeader: { flexDirection: 'row-reverse', justifyContent: 'space-between', alignItems: 'center', marginTop: 28, marginBottom: 8, paddingHorizontal: 16 },
  sectionTitle: { color: DARK, fontSize: 18, fontWeight: '700' },
  link: { color: BLUE, fontSize: 14 },
  tx: { flexDirection: 'row-reverse', alignItems: 'center', backgroundColor: '#fff', marginHorizontal: 16, marginTop: 8, padding: 12, borderRadius: 12 },
  txIcon: { width: 40, height: 40, borderRadius: 20, backgroundColor: BG, alignItems: 'center', justifyContent: 'center' },
  txName: { color: DARK, fontSize: 15, textAlign: 'right' },
  txDate: { color: GRAY, fontSize: 12, textAlign: 'right', marginTop: 2 },
  txAmount: { fontSize: 15, fontWeight: '700' },

  formCard: { backgroundColor: '#fff', margin: 16, borderRadius: 16, padding: 16, elevation: 3, shadowColor: '#000', shadowOpacity: 0.08, shadowRadius: 8, borderTopWidth: 3, borderTopColor: GOLD },
  hint: { color: BLUE, fontSize: 14, fontWeight: '600', textAlign: 'right' },
  fieldLabel: { color: GRAY, fontSize: 14, textAlign: 'right', marginTop: 16, marginBottom: 6 },
  input: { borderWidth: 1, borderColor: '#CBD5E1', borderRadius: 12, paddingHorizontal: 12, paddingVertical: 10, fontSize: 16, color: DARK, textAlign: 'right', backgroundColor: BG },
  ripRow: { flexDirection: 'row-reverse', alignItems: 'center', gap: 8 },
  scanBtn: { width: 48, height: 48, borderRadius: 14, alignItems: 'center', justifyContent: 'center', borderWidth: 1.5, borderColor: GOLD },
  scanOk: { color: GREEN, fontSize: 13, textAlign: 'right', marginTop: 6 },
  error: { color: RED, fontSize: 14, textAlign: 'right', marginTop: 12 },
  btn: { borderRadius: 14, paddingVertical: 14, alignItems: 'center', borderWidth: 1.5, borderColor: GOLD },
  btnText: { color: '#fff', fontSize: 16, fontWeight: '700' },
  successIcon: { width: 80, height: 80, borderRadius: 40, backgroundColor: GREEN, alignItems: 'center', justifyContent: 'center', alignSelf: 'center', marginTop: 8 },
  successTitle: { color: DARK, fontSize: 20, fontWeight: '700', textAlign: 'center', marginTop: 16 },
  successText: { color: GRAY, fontSize: 13, textAlign: 'center', marginTop: 4 },
  successAmount: { color: BLUE, fontSize: 26, fontWeight: '800', textAlign: 'center', marginTop: 12 },

  payIcon: { width: 96, height: 96, borderRadius: 28, backgroundColor: DEEP, alignItems: 'center', justifyContent: 'center', alignSelf: 'center', marginTop: 8, borderWidth: 2, borderColor: GOLD },
  merchantBox: { flexDirection: 'row-reverse', alignItems: 'center', marginTop: 16, padding: 12, borderRadius: 14, backgroundColor: '#E6EEFA', borderWidth: 1, borderColor: 'rgba(255,184,0,0.6)' },
  merchantIcon: { width: 48, height: 48, borderRadius: 14, backgroundColor: DEEP, alignItems: 'center', justifyContent: 'center' },
  merchantName: { color: DARK, fontSize: 17, fontWeight: '700', textAlign: 'right' },
  merchantRip: { color: GRAY, fontSize: 13, textAlign: 'right', marginTop: 2 },

  chips: { flexDirection: 'row-reverse', gap: 8, paddingHorizontal: 16, marginTop: 16, marginBottom: 4 },
  chip: { paddingVertical: 8, paddingHorizontal: 16, borderRadius: 20, backgroundColor: '#E6EEFA' },
  chipActive: { backgroundColor: BLUE },
  chipText: { color: BLUE, fontSize: 14, fontWeight: '600' },
  empty: { color: GRAY, textAlign: 'center', marginTop: 40, fontSize: 15 },

  overlay: { flex: 1, backgroundColor: 'rgba(0,0,0,0.55)', alignItems: 'center', justifyContent: 'center', padding: 24 },
  qrCard: { backgroundColor: '#fff', borderRadius: 20, padding: 20, alignItems: 'center', width: '100%', borderTopWidth: 4, borderTopColor: GOLD },
  qrTitle: { color: DARK, fontSize: 18, fontWeight: '700' },
  qrSub: { color: GRAY, fontSize: 13, textAlign: 'center', marginTop: 4 },
  qrBox: { marginTop: 16, padding: 14, borderRadius: 16, borderWidth: 2, borderColor: GOLD, backgroundColor: '#fff' },
  qrRip: { color: DARK, fontSize: 17, fontWeight: '600', marginTop: 14, marginBottom: 10 },

  permBox: { flex: 1, alignItems: 'center', justifyContent: 'center', padding: 24 },
  permText: { color: '#fff', fontSize: 16, textAlign: 'center', marginTop: 12 },
  scanOverlay: { ...StyleSheet.absoluteFillObject, alignItems: 'center', justifyContent: 'center' },
  scanFrame: { width: 250, height: 250, borderRadius: 24, borderWidth: 3, borderColor: GOLD, backgroundColor: 'rgba(255,255,255,0.05)' },
  scanHint: { color: '#fff', fontSize: 15, marginTop: 20, textAlign: 'center' },
  scanError: { color: '#FCA5A5', fontSize: 14, marginTop: 10, textAlign: 'center', paddingHorizontal: 24 },
  scanClose: { position: 'absolute', top: 50, right: 20, width: 44, height: 44, borderRadius: 22, backgroundColor: 'rgba(0,0,0,0.5)', alignItems: 'center', justifyContent: 'center' },

  nav: { position: 'absolute', bottom: 0, left: 0, right: 0, height: 80, backgroundColor: '#fff', flexDirection: 'row-reverse', justifyContent: 'space-around', alignItems: 'center', paddingBottom: 12, elevation: 12, shadowColor: '#000', shadowOpacity: 0.1, shadowRadius: 8, borderTopWidth: 2, borderTopColor: GOLD },
  tab: { alignItems: 'center', width: 64 },
  tabLabel: { fontSize: 11, marginTop: 2 },
  activeDot: { width: 5, height: 5, borderRadius: 3, backgroundColor: GOLD, marginTop: 3 },
  centerWrap: { marginTop: -28 },
  centerBtn: { width: 62, height: 62, borderRadius: 31, alignItems: 'center', justifyContent: 'center', borderWidth: 3, borderColor: GOLD },

  badge: { position: 'absolute', top: -4, right: -4, minWidth: 18, height: 18, borderRadius: 9, backgroundColor: RED, alignItems: 'center', justifyContent: 'center', paddingHorizontal: 4 },
  badgeText: { color: '#fff', fontSize: 10, fontWeight: '700' },
});
